#!/bin/bash
ruta=/home/pablo/Imágenes/Wallpapers
i=$(ls -1 $ruta | wc -l)
aleatorio1=$((1 + RANDOM % i))
aleatorio2=$((1 + RANDOM % i))
string1=$(ls $ruta | head -$aleatorio1 | tail -1)
string2=$(ls $ruta | head -$aleatorio2 | tail -1)

gsettings set org.gnome.desktop.background picture-uri "file:////$ruta/$string1"
gsettings set org.gnome.desktop.screensaver picture-uri "file:///$ruta/$string2"
 

#echo "Hay $i archivos, el aleatorio es $aleatorio, y el archivo, $string"

#Lanzado desde /etc/systemd/system/randomwallpapers.service
#systemctl enable randomwallpapers.service
